//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VumbaSoft.Masterdetails.Resources.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Pages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Pages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VumbaSoft.Masterdetails.Resources.Shared.Pages", typeof(Pages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account creation.
        /// </summary>
        public static string AdministrationAccountsCreate {
            get {
                return ResourceManager.GetString("AdministrationAccountsCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account details.
        /// </summary>
        public static string AdministrationAccountsDetails {
            get {
                return ResourceManager.GetString("AdministrationAccountsDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account edit.
        /// </summary>
        public static string AdministrationAccountsEdit {
            get {
                return ResourceManager.GetString("AdministrationAccountsEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts.
        /// </summary>
        public static string AdministrationAccountsIndex {
            get {
                return ResourceManager.GetString("AdministrationAccountsIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role creation.
        /// </summary>
        public static string AdministrationRolesCreate {
            get {
                return ResourceManager.GetString("AdministrationRolesCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role deletion.
        /// </summary>
        public static string AdministrationRolesDelete {
            get {
                return ResourceManager.GetString("AdministrationRolesDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role details.
        /// </summary>
        public static string AdministrationRolesDetails {
            get {
                return ResourceManager.GetString("AdministrationRolesDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role edit.
        /// </summary>
        public static string AdministrationRolesEdit {
            get {
                return ResourceManager.GetString("AdministrationRolesEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string AdministrationRolesIndex {
            get {
                return ResourceManager.GetString("AdministrationRolesIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string AuthLogin {
            get {
                return ResourceManager.GetString("AuthLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recover.
        /// </summary>
        public static string AuthRecover {
            get {
                return ResourceManager.GetString("AuthRecover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string AuthReset {
            get {
                return ResourceManager.GetString("AuthReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string HomeError {
            get {
                return ResourceManager.GetString("HomeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string HomeIndex {
            get {
                return ResourceManager.GetString("HomeIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Found.
        /// </summary>
        public static string HomeNotFound {
            get {
                return ResourceManager.GetString("HomeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized.
        /// </summary>
        public static string HomeUnauthorized {
            get {
                return ResourceManager.GetString("HomeUnauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cities Creation.
        /// </summary>
        public static string LookupSettingsCitiesCreate {
            get {
                return ResourceManager.GetString("LookupSettingsCitiesCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cities Deletion.
        /// </summary>
        public static string LookupSettingsCitiesDelete {
            get {
                return ResourceManager.GetString("LookupSettingsCitiesDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cities Details.
        /// </summary>
        public static string LookupSettingsCitiesDetails {
            get {
                return ResourceManager.GetString("LookupSettingsCitiesDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cities Edit.
        /// </summary>
        public static string LookupSettingsCitiesEdit {
            get {
                return ResourceManager.GetString("LookupSettingsCitiesEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cities Exporting.
        /// </summary>
        public static string LookupSettingsCitiesExport {
            get {
                return ResourceManager.GetString("LookupSettingsCitiesExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cities .
        /// </summary>
        public static string LookupSettingsCitiesIndex {
            get {
                return ResourceManager.GetString("LookupSettingsCitiesIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cities Printing.
        /// </summary>
        public static string LookupSettingsCitiesPrint {
            get {
                return ResourceManager.GetString("LookupSettingsCitiesPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Countries Creation.
        /// </summary>
        public static string LookupSettingsCountriesCreate {
            get {
                return ResourceManager.GetString("LookupSettingsCountriesCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Countries Deletion.
        /// </summary>
        public static string LookupSettingsCountriesDelete {
            get {
                return ResourceManager.GetString("LookupSettingsCountriesDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Countries Details.
        /// </summary>
        public static string LookupSettingsCountriesDetails {
            get {
                return ResourceManager.GetString("LookupSettingsCountriesDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Countries Edit.
        /// </summary>
        public static string LookupSettingsCountriesEdit {
            get {
                return ResourceManager.GetString("LookupSettingsCountriesEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Countries Exporting.
        /// </summary>
        public static string LookupSettingsCountriesExport {
            get {
                return ResourceManager.GetString("LookupSettingsCountriesExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Countries .
        /// </summary>
        public static string LookupSettingsCountriesIndex {
            get {
                return ResourceManager.GetString("LookupSettingsCountriesIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Countries Printing.
        /// </summary>
        public static string LookupSettingsCountriesPrint {
            get {
                return ResourceManager.GetString("LookupSettingsCountriesPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to States Creation.
        /// </summary>
        public static string LookupSettingsStatesCreate {
            get {
                return ResourceManager.GetString("LookupSettingsStatesCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to States Deletion.
        /// </summary>
        public static string LookupSettingsStatesDelete {
            get {
                return ResourceManager.GetString("LookupSettingsStatesDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to States Details.
        /// </summary>
        public static string LookupSettingsStatesDetails {
            get {
                return ResourceManager.GetString("LookupSettingsStatesDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to States Edit.
        /// </summary>
        public static string LookupSettingsStatesEdit {
            get {
                return ResourceManager.GetString("LookupSettingsStatesEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to States Exporting.
        /// </summary>
        public static string LookupSettingsStatesExport {
            get {
                return ResourceManager.GetString("LookupSettingsStatesExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to States .
        /// </summary>
        public static string LookupSettingsStatesIndex {
            get {
                return ResourceManager.GetString("LookupSettingsStatesIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to States Printing.
        /// </summary>
        public static string LookupSettingsStatesPrint {
            get {
                return ResourceManager.GetString("LookupSettingsStatesPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile deletion.
        /// </summary>
        public static string ProfileDelete {
            get {
                return ResourceManager.GetString("ProfileDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile edit.
        /// </summary>
        public static string ProfileEdit {
            get {
                return ResourceManager.GetString("ProfileEdit", resourceCulture);
            }
        }
    }
}
